name: Commit Scores (Unreviewed)

on:
  workflow_run:
    workflows: [IV Curve Parameter Fit Scorer]
    types:
      - completed

jobs:
  commit-scores-to-database-unreviewed:
    name: Commit Scores (Unreviewed)
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download scores from scorer workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: parameter-fit-scorer.yaml
          repo: ${{ github.event.workflow_run.repository }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Validate score output
        # retrive output from parameter-fit-scorer and validate/sanitize it
        run: ls -R
      - name: Commit to database
        if: ${{ github.repository_owner == 'cwhanse' }}
        run: echo 'Scores recorded'

